version: "3"

services:
  api:  
    build: api/
    container_name: lock-manager-api
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - api_data:/usr/app/api
    networks:
      - lockManager
    depends_on:
      - db
    env_file:
      - .env

  db:
    image: mysql:8.0
    container_name: lock-manager-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Mysql.Root.123
      MYSQL_DATABASE: lockmanager
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - lockManager


volumes:
  api_data:
  db_data:

networks:
  lockManager: