version: "3"

services:
  db:
    image: mysql:8.0
    container_name: lock-manager-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Mysql.Root.123
      MYSQL_DATABASE: lockmanager
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    ports:
      - "3307:3306"
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -umyuser -pmysqpassword"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
    volumes:
      - db_data:/var/lib/mysql


  api:
    build: ./api
    container_name: lock-manager-api
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - api_data:/usr/app/api
      - ./logs:/usr/app/api/logs 
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env

volumes:
  api_data:
  db_data:
  logs: