FROM node:20.11.0 AS builder

WORKDIR /front

COPY package*.json ./
RUN npm install

COPY . .
RUN npm run build

# Etapa de produção com Nginx
FROM nginx:1.25.3-alpine

# Copia o build para o diretório padrão do Nginx
COPY --from=builder /front/dist /usr/share/nginx/html

# Copia a configuração personalizada do Nginx
COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]