# Etapa de build
FROM node:20.11.0 AS builder

WORKDIR /front

COPY package*.json ./
RUN npm install


COPY . .
RUN npm run build

# Etapa de execução
FROM node:20.11.0 AS runner

WORKDIR /front

COPY --from=builder /front/dist ./dist
RUN npm install -g serve

CMD ["serve", "-s", "dist", "-l", "80"]
