FROM node:latest

WORKDIR /usr/app/api

COPY package*.json ./
RUN npm install

COPY . .
RUN npm run build

# Instalar o cliente MySQL
RUN apt-get update && apt-get install -y mysql-client

COPY wait-for-db.sh /usr/local/bin/wait-for-db.sh
RUN chmod +x /usr/local/bin/wait-for-db.sh

EXPOSE 3000

ENTRYPOINT ["wait-for-db.sh", "npm", "start"]
